on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Windows build
# jobs:
#     test-windows:
#         runs-on: windows-latest
jobs:
    test-windows:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }} (${{ matrix.python-version}})
        strategy:
            fail-fast: false
            matrix:
              os: ["windows-latest"]
              python-version: ["3.7","3.8"]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install --user -r requirements.txt
                  pip install --user -r requirements_dev.txt
                  pip install .
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/


        # steps:
        #   - name: Checkout code
        #     uses: actions/checkout@v3
      
        #   - name: Set up Python
        #     uses: actions/setup-python@v4
        #     with:
        #       python-version: ${{ matrix.python-version}}
              
        #   - name: Install GDAL
        #         run: conda install -c conda-forge gdal --yes
        # - name: Test GDAL installation
        #         run: |
        #             python -c "from osgeo import gdal"
        #             gdalinfo --version
        #     - name: Install dependencies
        #         run: |
        #             python -m pip install --upgrade pip
        #             pip install --no-cache-dir Cython
        #             pip install -r requirements.txt
        #             pip install .


        # steps:
        #     - uses: actions/checkout@v3
        #     - name: Install miniconda
        #       uses: conda-incubator/setup-miniconda@v2
        #       with:
        #           auto-activate-base: true
        #           python-version: "3.8"
        #     - name: Install GDAL
        #       run: conda install -c conda-forge gdal --yes
        #     - name: Test GDAL installation
        #       run: |
        #           python -c "from osgeo import gdal"
        #           gdalinfo --version
        #     - name: Install dependencies
        #       run: |
        #           python -m pip install --upgrade pip
        #           pip install --no-cache-dir Cython
        #           pip install -r requirements.txt
        #           pip install .
